import type { Metadata } from "next";
import {Georama} from "next/font/google";;
import "./globals.css";

const georama = Georama({
  variable: "--font-georama-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Weather App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${georama.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
