import type { Metadata } from "next";
import {Georama} from "next/font/google";;
import "./globals.css";

const georama = Georama({
  variable: "--font-georama-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Weather App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <head>
      <link
  rel="icon"
  href="/favicon-32x32.png"
  type="image/png"
  sizes="32x32"
/>
<link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'/>
      </head> */}
      <body
        className={`${georama.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
